name: "Execute Bash Command"
inputs:
    host:
        required: true
    port:
        required: true
        default: 22
    user:
        required: true
    ssh_key_text:
        description: "SSH private key text"
        required: true
    script:
        required: true
# fixme: finish this action
runs:
    using: "composite"
    steps:
        - name: "Execute bash command"
          shell: bash
          run: |
              function create_private_keyfile_from_content() {
                content="$1"
                key_file_path="$2"
                mkdir -p $(dirname $key_file_path)
                touch $key_file_path && chmod 600 $key_file_path
                >$key_file_path
                echo "$content" >>$key_file_path
                echo $key_file_path
              }          

              keyfile_path=${{ github.workspace }}/$(date +%s)_key

              create_private_keyfile_from_content "${{inputs.ssh_key_text}}" "$keyfile_path"

              if [[ ${{ inputs.direction }} == "download" ]]; then
                scp -o StrictHostKeyChecking=no -P ${{ inputs.port }} -i $keyfile_path ${{ inputs.user }}@${{ inputs.host }}:${{ inputs.server_file }} ${{ inputs.local_file }}
              else
                scp -o StrictHostKeyChecking=no -P ${{ inputs.port }} -i $keyfile_path ${{ inputs.local_file }} ${{ inputs.user }}@${{ inputs.host }}:${{ inputs.server_file }}
              fi
