run-name: ${{inputs.repo_name}} - Update the latest Docker images on the servers.
on:
    workflow_dispatch:
        inputs:
            repo_name:
                required: true
                type: string
            branch:
                required: true
                type: string
jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        environment: ${{inputs.repo_name}}/${{inputs.branch}}
        steps:
            - uses: actions/checkout@v4

            - name: " Update latest docker images on the server"
              uses: ./.github/actions/ssh-script
              with:
                  host: ${{vars.SERVER_HOST}}
                  port: ${{vars.SERVER_SSH_PORT}}
                  user: ${{vars.SERVER_USER}}
                  ssh_key_text: ${{ secrets.SERVER_PRIVATE_KEY }}
                  script: |
                      repo_owner=$(echo "${{inputs.repo_name}}" | cut -d'/' -f1)
                      echo "here ===>"
                      echo $repo_owner

                      docker login -u $repo_owner -p ${{ env.GH_TOKEN }} ghcr.io
                      cd ${{ vars.SERVER_DEPLOY_PATH }}
                      docker compose pull
                      docker compose down
                      docker compose up -d
                      docker image prune -a -f
                      docker logout ghcr.io
