name: build-docker-image
on:
    workflow_dispatch:
        inputs:
            repo_name:
                required: true
                type: string
            commit_sha:
                required: true
                type: string
            target_branch:
                required: true
                type: string

env:
    REPO_PATH: ${{ github.workspace }}
    BUILD_PATH: ${{ github.workspace }}/.build

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        environment: ${{inputs.repo_name}}/${{github.event.repository.default_branch}}
        steps:
            - name: Checkout private repo
              uses: actions/checkout@v4
              with:
                  repository: ${{ inputs.repo_name }}
                  ssh-key: ${{ secrets.SSH_KEY_GITHUB }}
                  path: ${{ env.REPO_PATH }}
                  ref: ${{ inputs.commit_sha }}
                  fetch-depth: 1

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build & Publish image
              run: |
                  echo ${{github.event.repository.default_branch}}
                  cd ${{ env.BUILD_PATH }}
                  docker build -t ${{ env.ODOO_IMAGE_TAG }} .
                  docker push ${{ env.ODOO_IMAGE_TAG }}
