run-name: ${{inputs.repo_name}} - Build docker image
on:
    workflow_dispatch:
        inputs:
            repo_name:
                required: true
                type: string
            commit_sha:
                required: true
                type: string
            default_branch:
                required: true
                type: string

env:
    REPO_PATH: ${{ github.workspace }}
    BUILD_PATH: ${{ github.workspace }}/.build

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        environment: ${{inputs.repo_name}}/${{inputs.default_branch}}
        steps:
            - name: Checkout project source
              uses: actions/checkout@v4
              with:
                  repository: ${{ inputs.repo_name }}
                  ssh-key: ${{ secrets.SSH_KEY_GITHUB }}
                  path: ${{ env.REPO_PATH }}
                  ref: ${{ inputs.commit_sha }}
                  fetch-depth: 1

            - name: Login to GitHub container registry
              run: |
                  repo_owner=$(echo "${{inputs.repo_name}}" | cut -d'/' -f1)
                  echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u $repo_owner --password-stdin

            - name: Build image
              run: |
                  cd ${{ env.BUILD_PATH }}
                  docker build . \
                        --tag ghcr.io/${{inputs.repo_name}} \
                        --label "org.opencontainers.image.source=https://github.com/${{inputs.repo_name}}" \
                        --label "github.run.id=${GITHUB_RUN_ID}"

            - name: Publish image to GitHub container registry
              run: |
                  docker push ghcr.io/${{inputs.repo_name}}

            - name: Remove untagged (old) image from GitHub container registry
              uses: ./.github/actions/delete-untagged-packages
              with:
                  github_token: ${{ secrets.GH_TOKEN }}
                  repo_name: ${{ inputs.repo_name }}
